.gitignore
ocean-climate-simulation/data_free_ocean_climate_simulation.jl

This PR adds a script which has the same kernels as `ocean_climate_simulation.jl` but does not require downloading data.
@wsmoses

Add a new script to do a pseudo-climate simulation with no data requirements

---

.github/dependabot.yml
.github/workflows/CI.yml

I accidentally pushed the previous commit to `main` instead of a new branch, so here we go opening a PR to continue working on the CI setup.

Add new CI setup

---

Project.toml
ocean-climate-simulation/data_free_ocean_climate_simulation.jl
ocean-climate-simulation/ocean_climate_simulation_mlir.jl

@wsmoses one thing which isn't clear to me is that the new keyword is only applied to the `@code_hlo` macro calls, not when we actually run the code. How do you expect that to be applied there?
Fix #21.

Use new `raise=true` keyword

---

Project.toml

While waiting for https://github.com/CliMA/Oceananigans.jl/pull/4151 to resolve the compat issues with Reactant.

Pin Oceananigans to last known working version

---

ocean-climate-simulation/data_free_ocean_climate_simulation.jl

Pass more arguments to the model init function

---

.github/workflows/CI.yml
Project.toml
ocean-climate-simulation/ocean_climate_simulation_mlir.jl
src/GordonBell25.jl
src/data_free_ocean_climate_simulation.jl
src/precompile.jl

Not thoroughly tested yet, opening as a draft to save the progress.

Turn data_free_ocean_climate_simulation.jl script into a package

---

ocean-climate-simulation/ocean_climate_simulation_mlir.jl

Reduce `Ninner` to 2

---

.github/workflows/CI.yml

Run CI jobs with IFRT runtime too

---

.github/workflows/CompileOrRun.yml

Try to work around https://github.com/julia-actions/cache/issues/161

[CI] Make cache restore key more unique

---

.github/workflows/Run.yml

It was working fine yesterday, today it started having memory issues.  Will investigate later if time.

[GHA] Disable new extra job for now

---

ocean-climate-simulation/ocean_climate_simulation_run.jl

Ref: https://github.com/EnzymeAD/Reactant.jl/pull/962.

Compile function to be profiled with `sync=true`

---

.github/workflows/Compile.yml
.github/workflows/Run.yml
.gitignore
sharding/sharded_baroclinic_instability.jl
sharding/sharded_tripolar_instability.jl
simulations/baroclinic_instability_simulation_compile.jl
simulations/baroclinic_instability_simulation_run.jl
simulations/ocean_climate_simulation_compile.jl
simulations/ocean_climate_simulation_run.jl
src/GordonBell25.jl
src/timestepping_utils.jl

Add common timestepping methods in src

---

sharding/sharded_baroclinic_instability_simulation_run.jl
sharding/simple_sharding_problem.jl

@glwagner @simone-silvestri I haven't tested it at all yet, but this should be a way to make the script closer to the simple sharding one in terms of organisation.

Improve baroclinic script with sharding

---

sharding/less_simple_sharding_problem.jl
sharding/simple_sharding_problem.jl

Less simple sharding problem

---

.gitignore
container-alps/Containerfile
container-alps/Containerfile-base
container-alps/LocalPreferences-base.toml
container-alps/LocalPreferences.toml
container-alps/README.md
container-alps/build.sh
container-alps/reactant.toml

I need to polish this, opening as a draft to save the progress.

Build container(s) for use on Alps

---

Project.toml
src/baroclinic_instability_model.jl
src/model_utils.jl

This may not be necesssary if https://github.com/CliMA/Oceananigans.jl/pull/4363 lands but just in case

Add custom function for initializing the baroclinic instability model

---

simulations/baroclinic_instability_simulation_compile.jl
simulations/ocean_climate_simulation_compile.jl
src/correctness.jl
src/sharding_utils.jl
src/timestepping_utils.jl

Other improvements to CI setup

---

sharding/less_simple_sharding_problem.jl
sharding/sharded_baroclinic_instability_simulation_run.jl
sharding/simple_sharding_problem.jl
src/sharding_utils.jl

Define `get_jobid_procid()` function in `GordonBell25` module

---

.github/workflows/CompileOrRun.yml
sharding/sharded_baroclinic_instability_simulation_compile.jl
simulations/baroclinic_instability_simulation_compile.jl
simulations/ocean_climate_simulation_compile.jl

Ref: https://github.com/PRONTOLab/GB-25/pull/178#discussion_r2040755814.

Actually use sharded model in sharded baroclinic problem

---

sharding/less_simple_sharding_problem.jl
sharding/sharded_baroclinic_instability_simulation_run.jl
sharding/simple_sharding_problem.jl

We don't like dus-to-concat anymore.

Remove some useless (if not harmful) compiler options

---

correctness/correctness_sharded_baroclinic_instability_simulation_run.jl

Use larger grid for testing correctness of sharded baroclinic model

---

correctness/correctness_baroclinic_instability_simulation_run.jl
correctness/correctness_sharded_baroclinic_instability_simulation_run.jl

Set `atol` to 0 for correctness tests

---

Project.toml
simulations/ocean_climate_simulation.jl
src/model_utils.jl

@glwagner My understanding is that this package isn't actually used anywhere, is that correct?

Remove unused `CFTime` from project

---

correctness/correctness_baroclinic_instability_simulation_run.jl

Use a larger grid also for serial correctness tests

---

.github/workflows/Run.yml

Ref https://github.com/EnzymeAD/Reactant.jl/issues/1551#issuecomment-3221535744

Reduce earlyoom threshold from 4 to 2
